KEEPALIVED_CONFD_NODES: https://etcd-host:2379
KEEPALIVED_CONFD_CMD_ARGS: -backend etcd -interval 10 -log-level debug

KEEPALIVED_CONFD_CLIENT_TLS: false
KEEPALIVED_CONFD_CLIENT_CAKEYS_FILENAME:
KEEPALIVED_CONFD_CLIENT_CERT_FILENAME:
KEEPALIVED_CONFD_CLIENT_KEY_FILENAME:

KEEPALIVED_CONFD_KUBERNETES_SERVICE_NAMESPACE: default
KEEPALIVED_CONFD_KUBERNETES_SERVICE_NAME: keepalived
KEEPALIVED_CONFD_KUBERNETES_NODE_NAME:

KEEPALIVED_CONFD_CLIENT_SSL_HELPER_PREFIX: confd
SSL_HELPER_AUTO_RENEW_SERVICES_IMPACTED: confd
