KEEPALIVED_CONFD_RUN_ON_FLEET_NODE_METADATA_KEY: keepalived
KEEPALIVED_CONFD_RUN_ON_FLEET_NODE_METADATA_VALUE: true

KEEPALIVED_CONFD_ETCD_NODES: https://etcd-host:2379
KEEPALIVED_CONFD_INTERVAL: 10

KEEPALIVED_CONFD_CLIENT_CAKEYS_FILENAME:
KEEPALIVED_CONFD_CLIENT_CERT_FILENAME:
KEEPALIVED_CONFD_CLIENT_KEY_FILENAME:


KEEPALIVED_CONFD_LOG_LEVEL: debug
